apiVersion: v1
kind: Service
metadata:
  name: go-clean-boilerplate
  labels:
    app: go-clean-boilerplate
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: go-clean-boilerplate
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: go-clean-boilerplate-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - api.example.com
    secretName: go-clean-boilerplate-tls
  rules:
  - host: api.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: go-clean-boilerplate
            port:
              number: 80
